AllCops:
  RunRailsCops: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'vendor/bundle/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'log/**/*'
Metrics/LineLength:
  Max: 99
Metrics/AbcSize:
  Max: 20
Documentation:
  Enabled: false